/** Field Service Ledger style: inspect a local APK before enabling install. */
import { Button } from "@/components/ui/button";
import { inspectApk, type ApkInspection } from "@/lib/apkInspector";
import { AlertTriangle, BadgeCheck, FileArchive, Loader2, LockKeyhole, ShieldCheck, Upload } from "lucide-react";
import { useState } from "react";

export function ApkInspectionWorkspace({ language, isLive, install }: { language: "en" | "ar" | "other"; isLive: boolean; install: (file?: File) => Promise<void> }) {
  const ar = language === "ar";
  const [file, setFile] = useState<File | null>(null);
  const [inspection, setInspection] = useState<ApkInspection | null>(null);
  const [error, setError] = useState("");
  const [inspecting, setInspecting] = useState(false);
  const [installing, setInstalling] = useState(false);
  const choose = async (candidate?: File) => {
    setFile(candidate || null); setInspection(null); setError("");
    if (!candidate) return;
    setInspecting(true);
    try { setInspection(await inspectApk(candidate)); } catch (reason) { setError(reason instanceof Error ? reason.message : "APK inspection failed."); } finally { setInspecting(false); }
  };
  const continueInstall = async () => { setInstalling(true); try { await install(file || undefined); } finally { setInstalling(false); } };
  const cert = inspection?.certificate;
  return <section className="space-y-5">
    <div className="service-card p-6"><p className="kicker text-[#687584]">{ar ? "فحص محلي قبل التثبيت" : "Local pre-install inspection"}</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.05em]">{ar ? "افحص ملف APK قبل أن يصل إلى الجهاز." : "Inspect an APK before it reaches the device."}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#526273]">{ar ? "تُقرأ بيانات الحزمة والأذونات وكتلة التوقيع المتاحة داخل هذا المتصفح. لا يُرفع ملف APK. لا يصبح التثبيت متاحاً حتى يكتمل الفحص." : "Package metadata, declared permissions, and any available signature block are read inside this browser. The APK is not uploaded. Installation stays unavailable until inspection completes."}</p><label className="action-button mt-6 inline-flex items-center border border-[#14253a] bg-[#14253a] px-4 py-3 text-sm font-semibold text-[#f6f2ea]"><Upload className="mr-2" size={16} />{ar ? "اختيار وفحص APK" : "Choose & inspect APK"}<input type="file" accept=".apk,application/vnd.android.package-archive" className="sr-only" onChange={(event) => choose(event.target.files?.[0])} /></label>{file && <p className="mono mt-4 text-[0.68rem] text-[#687584]">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</p>}</div>
    {inspecting && <div className="service-card flex items-center gap-3 p-5"><Loader2 className="animate-spin text-[#59869c]" size={20} /><p className="text-sm">{ar ? "يتم فحص الحزمة والأذونات والتوقيع محلياً…" : "Inspecting package, permissions, and signature locally…"}</p></div>}
    {error && <div className="border-l-2 border-[#d39152] bg-[#fff2e1] p-5 text-sm leading-6 text-[#6d5133]"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0" size={19} /><p>{error}</p></div></div>}
    {inspection && <>
      <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="service-card p-6"><div className="flex items-center justify-between"><div><p className="kicker text-[#687584]">{ar ? "هوية الحزمة" : "Package identity"}</p><h3 className="mt-1 text-xl font-bold">{inspection.packageName || (ar ? "غير متاح" : "Unavailable")}</h3></div><FileArchive className="text-[#59869c]" size={21} /></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="kicker text-[#687584]">{ar ? "الإصدار" : "Version"}</dt><dd className="mt-1 mono text-xs">{inspection.versionName || "—"}</dd></div><div><dt className="kicker text-[#687584]">{ar ? "رمز الإصدار" : "Version code"}</dt><dd className="mt-1 mono text-xs">{inspection.versionCode ?? "—"}</dd></div><div><dt className="kicker text-[#687584]">{ar ? "الأذونات المعلنة" : "Declared permissions"}</dt><dd className="mt-1 text-lg font-bold">{inspection.permissions.length}</dd></div><div><dt className="kicker text-[#687584]">{ar ? "أذونات حساسة" : "Sensitive permissions"}</dt><dd className={`mt-1 text-lg font-bold ${inspection.sensitivePermissions.length ? "text-[#934639]" : "text-[#527321]"}`}>{inspection.sensitivePermissions.length}</dd></div></dl></div><div className="service-card p-6"><div className="flex items-center justify-between"><div><p className="kicker text-[#687584]">{ar ? "شهادة التوقيع" : "Signing certificate"}</p><h3 className="mt-1 text-xl font-bold">{cert?.status === "available" ? (ar ? "تم تحليل شهادة v1" : "v1 certificate parsed") : (ar ? "فحص محدود للتوقيع" : "Limited signature inspection")}</h3></div><LockKeyhole className="text-[#59869c]" size={21} /></div><p className="mt-4 text-xs leading-5 text-[#526273]">{cert?.note}</p>{cert?.subject && <dl className="mono mt-4 space-y-2 break-all text-[0.68rem]"><div><dt className="text-[#687584]">{ar ? "الموضوع" : "Subject"}</dt><dd>{cert.subject}</dd></div><div><dt className="text-[#687584]">{ar ? "الجهة المُصدرة" : "Issuer"}</dt><dd>{cert.issuer}</dd></div><div><dt className="text-[#687584]">SHA-256</dt><dd>{cert.fingerprintSha256}</dd></div></dl>}</div></div>
      <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="service-card p-6"><div className="flex items-center gap-2"><ShieldCheck className="text-[#59869c]" size={18} /><div><p className="kicker text-[#687584]">{ar ? "الأذونات" : "Permissions"}</p><h3 className="mt-1 font-bold">{ar ? "راجع كل طلب قبل التثبيت." : "Review every request before installing."}</h3></div></div><div className="mt-5 flex flex-wrap gap-2">{inspection.permissions.length ? inspection.permissions.map((permission) => <span key={permission} className={`mono border px-2 py-1 text-[0.65rem] ${inspection.sensitivePermissions.includes(permission) ? "border-[#dba193] bg-[#fbe5df] text-[#934639]" : "border-[#d8d1c4] bg-[#f3efe6] text-[#526273]"}`}>{permission}</span>) : <p className="text-sm text-[#687584]">{ar ? "لم تُستخرج أذونات من البيان." : "No permissions were extracted from the manifest."}</p>}</div></div><div className="border-l-2 border-[#d39152] bg-[#fff2e1] p-5 text-sm leading-6 text-[#6d5133]"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0" size={19} /><p>{ar ? "يعرض الفحص شهادة JAR v1 المتاحة ولا يثبت ثقة الناشر أو يتحقق من مخططات توقيع APK الحديثة v2/v3/v4. افحص المصدر والشهادة قبل الاعتماد على الملف." : "The inspection displays an available v1 JAR certificate only; it does not establish publisher trust or validate modern v2/v3/v4 APK signature schemes. Review the source and certificate before relying on the file."}</p></div></div></div>
      {inspection.warnings.length > 0 && <div className="service-card p-5"><p className="kicker text-[#934639]">{ar ? "ملاحظات الفحص" : "Inspection notes"}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-[#6d3d35]">{inspection.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul></div>}
      <div className="flex flex-wrap items-center justify-between gap-4 border border-[#14253a] bg-[#14253a] p-5 text-[#f6f2ea]"><div><p className="kicker text-[#c8f04a]">{ar ? "قرار المشغّل" : "Operator decision"}</p><p className="mt-1 text-sm text-[#c7d3dc]">{ar ? "تم الفحص محلياً. تابع فقط إذا فهمت الأذونات وملاحظات التوقيع." : "Local inspection is complete. Continue only if you understand the permissions and signing notes."}</p></div><Button onClick={continueInstall} disabled={!isLive || installing} className="action-button bg-[#c8f04a] text-[#14253a] hover:bg-[#d7f66c]">{installing ? <Loader2 className="mr-2 animate-spin" size={16} /> : <BadgeCheck className="mr-2" size={16} />}{ar ? "تثبيت بعد المراجعة" : "Install after review"}</Button></div>
    </>}
  </section>;
}
